(define (make-table)
    (let ((local-table (list '*table)))

        (define (lookup key-1 key-2)
            (let ((subtable (assoc key-1 (cdr local-table))))
                (if subtable
                    (let ((record (assoc key-2 (cdr subtable))))
                        (if record
                            (cdr record)
                            false
                        )
                    )
                    false
                )
            )
        )
        
        (define (insert! key-1 key-2 value)
            (let ((subtable (assoc key-1 (cdr local-table))))
                (if subtable
                    (let ((record (assoc key-2 (cdr subtable))))
                        (if record
                            (set-cdr! record value)
                            (set-cdr! 
                                subtable
                                (cons (cons key-2 value) (cdr subtable))
                            )
                        )
                    )
                    (set-cdr! 
                        local-table
                        (cons 
                            (list key-1 (cons key-2 value))
                            (cdr local-table)
                        )
                    )
                )
            )
            'ok
        )

        (define (dispatch m)
            (cond 
                ((eq? m 'lookup-proc) lookup)
                ((eq? m 'insert-proc!) insert!)
                (else (error "Unknown operation -- TABLE" m))
            )
        )

        dispatch
    )
)
(define operation-table (make-table))
(define get (operation-table 'lookup-proc))
(define put (operation-table 'insert-proc!))

(define (attach-tag type-tag contents)
    (cons type-tag contents)
)
(define (type-tag datum)
    (if (pair? datum)
        (car datum)
        (error "Bad tagged datum -- TYPE-TAG" datum)
    )
)
(define (contents datum)
    (if (pair? datum)
        (cdr datum)
        (error "Bad tagged datum -- CONTENTS" datum)
    )
)

(define (apply-generic op . args)
    (let ((type-tags (map type-tag args)))
        (let ((proc (get op type-tags)))
            (if proc
                (apply proc (map contents args))
                (error 
                    "No method for these types -- APPLY-GENERIC"
                    (list op type-tags))))))

(define (variable? x) (symbol? x))
(define (same-variable? v1 v2)
    (and (variable? v1) (variable? v2) (eq? v1 v2)))

(define (install-scheme-number-package)
    (define (tag x)
        (attach-tag 'scheme-number x)
    )
    (put 'add '(scheme-number scheme-number)
        (lambda (x y) (tag (+ x y)))
    )
    (put 'sub '(scheme-number scheme-number)
        (lambda (x y) (tag (- x y)))
    )
    (put 'mul '(scheme-number scheme-number)
        (lambda (x y) (tag (* x y)))
    )
    (put 'div '(scheme-number scheme-number)
        (lambda (x y) (tag (/ x y)))
    )
    (put 'make 'scheme-number
        (lambda (x) (tag x))
    )
    (put '=zero? '(scheme-number)
        (lambda (value) (= value 0))
    )
    (put 'negate '(scheme-number)
        (lambda (x) (tag (- x)))
    )
    'done
)

(define (install-rational-package)
    (define (make x)
        (cons (car x) (cons (cadr x) (caddr x))))
    (define (numer x) (car x))
    (define (denom x) (cdr x))
    (define (make-rat n d)
        (let ((g (greatest-common-divisor n d)))
            (cons (make (div n g)) (make (div d g))))
    )
    (define (add-rat x y)
        (make-rat
            (add (mul (numer x) (denom y)) (mul (numer y) (denom x)))
            (mul (denom x) (denom y))
        )
    )

    (define (tag x)
        (attach-tag 'rational x)
    )
    (put 'add '(rational rational)
        (lambda (x y) (tag (add-rat x y)))
    )
    (put 'make 'rational
        (lambda (n d) (tag (make-rat n d)))
    )
    'done
)

(define (install-polynomial-package)
    (define (make-poly variable term-list)
        (cons variable term-list))
    (define (variable p) (car p))
    (define (term-list p) (cdr p))

    (define (adjoin-term term term-list)
        (if (=zero? (coeff term))
            term-list
            (cons term term-list)))
    (define (the-empty-termlist) '())
    (define (first-term term-list) (car term-list))
    (define (rest-terms term-list) (cdr term-list))
    (define (empty-termlist? term-list) (null? term-list))
    (define (make-term order coeff) (list order coeff))
    (define (order term) (car term))
    (define (coeff term) (cadr term))

    (define (negate-terms p)
        (map (lambda (term)
            (make-term (order term) (negate (coeff term)))
        ) p))

    (define (add-terms L1 L2)
        (cond
            ((empty-termlist? L1) L2)
            ((empty-termList? L2) L1)
            (else (let ((t1 (first-term L1)) (t2 (first-term L2)))
                (cond
                    ((> (order t1) (order t2))
                        (adjoin-term t1
                            (add-terms (rest-terms L1) L2)
                        )
                    )
                    ((< (order t1) (order t2))
                        (adjoin-term t2
                            (add-terms L1 (rest-terms L2))
                        )
                    )
                    (else (adjoin-term
                        (make-term (order t1)
                            (add (coeff t1) (coeff t2)))
                        (add-terms (rest-terms L1)
                            (rest-terms L2))
                    ))
                )
            ))
        )
    )

    (define (mul-terms L1 L2)
        (if (empty-termlist? L1)
            (the-empty-termlist)
            (add-terms (mul-term-by-all-terms (first-term L1) L2)
                (mul-terms (rest-terms L1) L2)
            )))
    (define (mul-term-by-all-terms t1 L)
        (if (empty-termlist? L)
            (the-empty-termlist)
            (let ((t2 (first-term L)))
                (adjoin-term
                    (make-term (+ (order t1) (order t2))
                        (mul (coeff t1) (coeff t2)))
                    (mul-term-by-all-terms t1 (rest-terms L)))
            ))
    )

    (define (div-terms L1 L2)
        (if (empty-termlist? L1)
            (list (the-empty-termlist) (the-empty-termlist))
            (let ((t1 (first-term L1)) (t2 (first-term L2)))
                (if (> (order t2) (order t1))
                    (list (the-empty-termlist) L1)
                    (let ((new-c (div (coeff t1) (coeff t2))) (new-o (- (order t1) (order t2))))
                        (let ((rest-of-result (add-terms L1 (negate-terms (mul-terms L2 (list (make-term new-o new-c)))))))
                            (let ((result (div-terms rest-of-result L2)))
                                (list (cons (make-term new-o new-c) (car result))
                                    (cadr result)))
                        ))))))
    (define (gcd-terms a b)
        (if (empty-termlist? b)
            a
            (gcd-terms b (remainder-terms a b))))
    (define (remainder-terms a b) (cadr (div-terms a b)))

    (define (add-poly p1 p2)
        (if (same-variable? (variable p1) (variable p2))
            (make-poly (variable p1)
                (add-terms (term-list p1)
                    (term-list p2)))
            (error "Polys not in same var -- ADD-POLY" (list p1 p2)))
    )
    (define (mul-poly p1 p2)
        (if (same-variable? (variable p1) (variable p2))
            (make-poly (variable p1)
                (mul-terms (term-list p1)
                    (term-list p2)))
            (error "Polys not in same var -- MUL-POLY" (list p1 p2)))
    )
    (define (div-poly p1 p2)
        (if (same-variable? (variable p1) (variable p2))
            (if (empty-termlist? (term-list p2))
                (error "Empty termlist -- DIV-POLY")
                (make-poly (variable p1)
                    (div-terms (term-list p1)(term-list p2))))
            (error "Polys not in same var -- DIV-POLY" (list p1 p2)))
    )
    (define (gcd-poly p1 p2)
        (if (same-variable? (variable p1) (variable p2))
            (make-poly (variable p1)
                (gcd-terms (term-list p1)
                    (term-list p2)))
            (error "Polys not in same var -- GCD-POLY" (list p1 p2)))
    )

    (define (tag p) (attach-tag 'polynomial p))
    (put 'add '(polynomial polynomial) (lambda (p1 p2) (tag (add-poly p1 p2))))
    (put 'sub '(polynomial polynomial)
        (lambda (p1 p2) (tag (add-poly p1 (make-poly (variable p2) (negate-terms (term-list p2)))))))
    (put 'mul '(polynomial polynomial)
        (lambda (p1 p2) (tag (mul-poly p1 p2))))
    (put 'make 'polynomial
        (lambda (var terms) (tag (make-poly var terms))))
    (put '=zero? '(polynomial)
        (lambda (value) (empty-termlist? (term-list value)))
    )
    (put 'negate '(polynomial)
        (lambda (p) (tag (make-poly (variable p) (negate-terms (term-list p))))))
    (put 'div '(polynomial polynomial) 
        (lambda (p1 p2) (tag (div-poly p1 p2))))
    (put 'greatest-common-divisor  '(polynomial polynomial) 
        (lambda (p1 p2) (tag (gcd-poly p1 p2))))
'done)

(define (add x y) (apply-generic 'add x y))
(define (sub x y) (apply-generic 'sub x y))
(define (mul x y) (apply-generic 'mul x y))
(define (div x y) (apply-generic 'div x y))
(define (=zero? x) (apply-generic '=zero? x))
(define (negate x) (apply-generic 'negate x))
(define (greatest-common-divisor x y) (apply-generic 'greatest-common-divisor x y))

(install-scheme-number-package)
(install-polynomial-package)
(install-rational-package)
(define (make-scheme-number n)
    ((get 'make 'scheme-number) n)
)
(define (make-rational n d)
    ((get 'make 'rational) n d))
(define (make-polynomial var terms)
    ((get 'make 'polynomial) var terms)
)

; (define a (make-polynomial 'y (list (list 5 (make-scheme-number 1)) (list 0 (make-scheme-number -1)))))
; (define b (make-polynomial 'y (list (list 2 (make-scheme-number 1)) (list 0 (make-scheme-number -1)))))
; (define c (make-polynomial 'y (list (list 1 (make-scheme-number 1)) (list 0 (make-scheme-number -1)))))
; (define d (make-polynomial 'y (list (list 1 (make-scheme-number 1)) (list 0 (make-scheme-number -2)))))
; (define e (make-polynomial 'y (list (list 3 (make-scheme-number 1)) (list 0 (make-scheme-number 7)))))

; (define p1 (make-polynomial 'x (list (list 2 (make-scheme-number 1)) (list 0 (make-scheme-number 1)))))
; (define p2 (make-polynomial 'x (list (list 3 (make-scheme-number 1)) (list 0 (make-scheme-number 1)))))

; (define rf (make-rational p2 p1))

; (define p1 (make-polynomial 'x  (list (list 4 (make-scheme-number 1)) (list 3 (make-scheme-number -1)) (list 2 (make-scheme-number -2)) (list 1 (make-scheme-number 2)))))
; (define p2 (make-polynomial 'x (list (list 3 (make-scheme-number 1)) (list 1 (make-scheme-number -1)))))
; (define rf (make-rational p1 p2))
; (greatest-common-divisor p1 p2)

(define p1 (make-polynomial 'x (list (list 2 (make-scheme-number 1)) (list 1 (make-scheme-number -2)) (list 0 (make-scheme-number 1)))))
(define p2 (make-polynomial 'x (list (list 2 (make-scheme-number 11)) (list 0 (make-scheme-number 7)))))
(define p3 (make-polynomial 'x (list (list 1 (make-scheme-number 13)) (list 0 (make-scheme-number 5)))))

(define q1 (mul p1 p2))
(define q2 (mul p1 p3))

(greatest-common-divisor q1 q2)
